### ISSUE TITLE
flow_parser won't convert from opam.

### ISSUE THREAD

**Issue by jordwalke** [esy-ocaml-old/esy-old#6]
`flow_parser` used to convert to package.json but now it doesn't with esy for some reason.

Error I see is:
```
Traceback (most recent call last):
  File "./bin/build-package", line 78, in <module>
    build_package(name, *versions)
  File "./bin/build-package", line 61, in build_package
    os.path.join(package_dir, name + '.' + version)
  File "/Users/jwalke/github/reasonml/esy/opam-packages-conversion/bin/lib.py", line 245, in generate_package_json
    buildFlatList(d["substs"]), breakList(d["build"]) + breakList(d["install"]))
  File "/Users/jwalke/github/reasonml/esy/opam-packages-conversion/bin/lib.py", line 95, in breakList
    terms = [unescapeTerm(term) for term in re.split(r"[\s\n]+", txt)]
  File "/Users/jwalke/github/reasonml/esy/opam-packages-conversion/bin/lib.py", line 74, in unescapeTerm
    return builtInVars[term]
KeyError: '"cd'
```

Here's an example version of the opam file for flow_parser.
```
opam-version: "1.2"
maintainer: "gabe@fb.com"
authors: [
  "Avik Chaudhuri"
  "Basil Hosmer"
  "Gabe Levi"
  "Jeff Morrison"
  "Marshall Roch"
  "Sam Goldman"
  "James Kyle"
]
homepage: "https://github.com/facebook/flow/tree/master/src/parser"
bug-reports: "https://github.com/facebook/flow/issues"
license: "BSD3"

build: [ "sh" "-c" "cd src/parser && make ocamlfind-install" ]

remove: ["ocamlfind" "remove" "flow_parser"]
depends: "ocamlfind" {build}
available: [ocaml-version >= "4.01.0"]
dev-repo: "https://github.com/facebook/flow.git"

```

**Comment by jordwalke** [comment]
Fixed and pushed.
